use_frameworks!

platform :ios, '10.0'

target 'YHPageViewControllerFramework_Example' do
  pod 'YHPageViewControllerFramework', :path => '../'

  target 'YHPageViewControllerFramework_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
